# Generated by Django 2.2.14 on 2021-09-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blood_Types',
        ),
    ]
