# Generated by Django 2.2.14 on 2021-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_blood_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_user',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
